"""empty message

Revision ID: c210d0379846
Revises: 3f8042e87414
Create Date: 2021-02-05 15:57:46.494488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c210d0379846'
down_revision = '3f8042e87414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=140), nullable=True))
    op.drop_column('post', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
